name: tawasul
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0


environment:
  sdk: ^3.6.0


dependencies:
  flutter_webrtc: ^0.13.1+hotfix.1
  sdp_transform: ^0.3.2
  provider: ^6.1.2
  keep_screen_on: ^4.0.0
  web_socket_channel: ^3.0.1
  get_it: ^8.0.3
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
